# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ea2301545744dd006f70b180a574bd24dcd2d0669b94d65552c91261b31e904a386ba3ea209695033eb71a902e2325a526a1d20299214d51136632d80c6052d

test:
  secret_key_base: 61a44f9155c27430ccca5c5bbca9b50ddc529d2b427b2b1bb99d72c301c626c1652aaccc95e3bd98943df46b000e98a3b3aa20cd651d6d0bb179e49174eb62f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
